hexapod_test_ubtech_servo_node:
  ros__parameters:
    log:
      log_level: debug
      log_path: ./log
      async: false
    serial_device: /dev/ttyS4
    baud_rate: 115200
    gpio_name: GPIO1_B1
