hexapod_ros2_control:
  ros__parameters:
    log:
      log_level: debug
      # Using none means closing the release log
      topic_log_level: none
      log_path: ./log
      # Is it an asynchronous log
      async: false
    msg_prefix: hexapod